### ISSUE TITLE
about data base connection with cluster

### ISSUE THREAD

**Issue by mahesh237** [ArchawinWongkittiruk/TrelloClone#3]
will  you tell me how to connect cluster i have already passed cluster url in mongoose .connect

const express = require('express');
const path = require('path');
const mongoose = require('mongoose');
const dotenv = require("dotenv");
dotenv.config();

const app = express();

// Connect database
(async function connectDB() {
  const MONGO_URI="mongodb+srv://trello:pL39mtQX9t4NVZRF@cluster0.mp7wk.mongodb.net/trello?retryWrites=true&w=majority"
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
      useFindAndModify: false,
    });
    console.log('MongoDB Connected...');
  } catch (err) {
    console.error(err.message);
    // Exit process with failure
    process.exit(1);
  }
})();

// Init middleware
app.use(express.json({ extended: false }));

// Define routes
app.use('/api/users', require('./routes/api/users'));
app.use('/api/auth', require('./routes/api/auth'));
app.use('/api/boards', require('./routes/api/boards'));
app.use('/api/lists', require('./routes/api/lists'));
app.use('/api/cards', require('./routes/api/cards'));
app.use('/api/checklists', require('./routes/api/checklists'));

// Serve static assets in production
if (process.env.NODE_ENV === 'production') {
  // Set static folder
  app.use(express.static('client/build'));

  app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, 'client', 'build', 'index.html'));
  });
}

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => console.log('Server started on port ' + PORT));

///it shows error first value must be  a string if i remove the first argument with string it runs properly but when i signup it tells user already exists please tell me how to solve this i am a begineer and in the process of learning

**Comment by ArchawinWongkittiruk** [comment]
You'll need to have a '.env' file in the root directory specifying the MONGO_URI

That's what the 'process.env.---' does; it finds values you specify in the '.env' file

Always gitignore your env files; these values should be secret to you

See the docs here https://www.npmjs.com/package/dotenv

**Comment by mahesh237** [comment]
Thank you so much you are great👍❤️❤️
